# Harmony Jekyll theme general configurations 

# Base URL
#baseurl: /harmony

# Site live URL
url: http://rombur.github.io

# Localhost 
#url: http://127.0.0.1:4000  

# Harmony theme configuration. Please change accordingly.
harmony:
  name: Data Transfer Kit (DTK)
  # Little description about your site
  description: Solution transfer for multiphysics simulations.
  # 'meta_description:' Write an awesome description for your new site here.
  # It will appear in your document head meta (for Google search results) and 
  # in your feed.xml site description.
  meta_description: > # 
    Solution transfer for multiphysics simulations.
  basetheme: theme-base-01 # pre defined thmes are darken, blue-water, redish.
  author: # Author details
    name: Gayan Virajith
    email: gayanvirajith@gmail.com
    url: http://gayanvirajith.github.io

  # Google Analytics key, leave blank to ignore
  google_analytics_key: UA-xxxx-x

  # Profile links, leave blank to ignore
  social: 
    github: ORNL-CEES/datatransferkit
    twitter:
    facebook:
    gplus: 
    dribble:
    pinterest: 
  # Toggle disclaimer in footer
  show_disclaimer: false

# Conversion / Build settings 
markdown:    kramdown
highlighter: rouge

# Permalinks
permalink:        pretty

exclude: 
  - CNAME
  - Gemfile
  - Rakefile
  - README.md
  - .gitignore
  - .sass-cache
  - Gemfile.lock

# Sass conversion configs
sass:
    sass_dir: assets/css/_sass
    style: :compressed
